from tests.adapters.mock_repository import FakeRepository
from tests.domain.mock_models import mock_order_line_generate, mock_order_line, mock_batch_generate, mock_batch_with_eta, mock_list_of_batches
